version: 2
jobs:
  build-and-test:
    macos:
      xcode: 12.5.1
    steps:
      - run:
          name: Run Build
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: CircleCIPractice

workflows:
  build: 
    jobs:
      - build-and-test
