version: 2
jobs:
    build-and-test:
        macos:
            xcode: "12.5.1"
        environment:
            FL_OUTPUT_DIR: output
        steps:
            - checkout

workflows:
    version: 2
    build:
        jobs:
            - build-and-test
