version: 2
jobs:
    build-and-test:
        macos:
            xcode: "12.5.1"
        environment:
            FL_OUTPUT_DIR: output
        steps:
            - checkout
            - run:
                name: pre-start simulator
                command: xcrun instruments -w "iPhone 11 Pro (13.3) [" || true
            - run:
                name: Build and run tests
                command: fastlane scan
                environment:
                    SCAN_DEVICE: iPhone 11 Pro
                    SCAN_SCHEME: TestProject
                    
            - store_test_results:
                path: output/scan
            - store_artifacts:
                path: output

workflows:
    version: 2
    build:
        jobs:
            - build-and-test
